### ISSUE TITLE
Problem using downloadGPM

### ISSUE THREAD

**Issue by hnbendini** [csaybar/gpm#1]
Thanks for the code! It is very useful. But unfortunately I´m having some problem with Axel, I guess. I have already set Axel as a enviroment variable on Windows configurations (I guess), but still given this error message: 

In addition: Warning messages:
1: running command 'axel -n 3 -s 504800 ftp://hnbendini@gmail.com:hnbendini@gmail.com@jsimpson.pps.eosdis.nasa.gov/NRTPUB/imerg/late/201601/3B-HHR-L.MS.MRG.3IMERG.20160101-S000000-E002959.0000.V03E.RT-H5 -o C:/Users/Hugo/Desktop/2016-01-01/3B-HHR-L.MS.MRG.3IMERG.20160101-S000000-E002959.0000.V03E.RT-H5' had status 127 
2: running command '"C:\Program Files\QGIS Lyon\bin\gdalinfo.exe" "C:/Users/Hugo/Desktop//2016-01-01/"' had status 1

**Comment by csaybar** [comment]
Hi!
If I just percatar that problem by running the code in Windows, the error is because you must declare also the "GDAL tools" as an environment variable, if you are working on Windows, the easiest option is to install Qgis and routing environment variables within the following folder "C:\Program Files\QGIS Wien\bin". Tell me how it goes.

regards

**Comment by hnbendini** [comment]
Thanks very much for your rapid reply!

I was trying to set the environment variable directly in the system. But I
am not sure if this is correct. It is attached a print screen showing how I
did. Am I have to set GDAL tools like this?

Thank you a lot!

2016-05-19 15:23 GMT-03:00 Cesar Luis Aybar Camacho <
notifications@github.com>:

> Hi!
> If I just percatar that problem by running the code in Windows, the error
> is because you must declare also the "GDAL tools" as an environment
> variable, if you are working on Windows, the easiest option is to install
> Qgis and routing environment variables within the following folder
> "C:\Program Files\QGIS Wien\bin". Tell me how it goes.
> 
> regards
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/AybarCL/GPM-data-management/issues/1#issuecomment-220409969

## 

_Hugo do Nascimento Bendini_

_Engenheiro Agrônomo (UNESP)_
_CREA-SP 5062905098_cel: (12) 98806-6386 (OI)
       (12) 98232-5189 (TIM)
_Mestre em Ciência da Computação (Embrapa Instrumentação/UFSCar)_
_Instrumentação Agropecuária/Processamento de Imagens e Sinais_
_Doutorando em Sensoriamento Remoto (INPE)_
_Divisão de Processamento de Imagens (DPI)_
ramal: (12) 3208-6805

**Comment by csaybar** [comment]
Hi,

the procedure for declaring environmental variables on Windows can find in this ".doc" 
[Donwload GPM DAY 1 WITH R.docx](https://github.com/AybarCL/GPM-data-management/files/275458/Donwload.GPM.DAY.1.WITH.R.docx)

if he did well, writing in the cmd "axel" and "gdal_translate" should give you something, if so happens the script should run smoothly.

![3fa0a46c-e04a-4637-aaf4-d9c95e9466ba](https://cloud.githubusercontent.com/assets/16768318/15442580/c203b838-1ea7-11e6-87d2-a977bc2fa079.png)
![unnamed](https://cloud.githubusercontent.com/assets/16768318/15442581/c3461362-1ea7-11e6-9a04-f398d4e6bd27.png)
